# Generated by Django 5.2.13 on 2026-04-23 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(choices=[('REMOTIVE', 'Remotive'), ('ADZUNA', 'Adzuna'), ('LINKEDIN', 'LinkedIn'), ('BRIGHTERMONDAY', 'BrighterMonday')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('tech_score', models.IntegerField(default=0)),
                ('location_score', models.IntegerField(default=0)),
                ('compatibility_score', models.IntegerField(default=0)),
                ('is_kenyan_friendly', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('raw_ai_evaluation', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_text', models.TextField()),
                ('preferred_tech_stack', models.JSONField(default=list)),
                ('location', models.CharField(default='Kenya', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
